version: "3.8"

services:
  iiif-content-search:
    build: .
    ports:
      - "8001:5000"
    environment:
      - LOG_LEVEL=DEBUG
      - SOLR_BASE_URL=https://solr2020.library.albany.edu:8984/solr
      - SOLR_CORE=iiif_content_search